---
- name: restart zookeeper
  systemd:
    name: zookeeper
    state: restarted
    daemon_reload: true
    enabled: true

- name: restart kafka
  systemd:
    name: kafka
    state: restarted
    daemon_reload: true
    enabled: true
