- name: ensure kafka directory exists
  file:
    path: "{{ kafka_dir }}"
    state: directory
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: http://mirrors.tuna.tsinghua.edu.cn/apache/kafka/{{ kafka_version }}/kafka_2.12-{{ kafka_version }}.tgz
    dest: "{{ kafka_dir }}"
    remote_src: yes
    creates: "{{ kafka_dir }}/kafka_2.12-{{ kafka_version }}"
    directory_mode: 0755
