---

- name: Ensure directory exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ kafka_dir }}"
    - "{{ zk_data_dir }}"
    - "{{ kafka_log_dirs }}"

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: http://mirrors.tuna.tsinghua.edu.cn/apache/kafka/{{ kafka_version }}/kafka_2.12-{{ kafka_version }}.tgz
    dest: "{{ kafka_dir }}"
    remote_src: yes
    creates: "{{ kafka_dir }}/kafka_2.12-{{ kafka_version }}"
    directory_mode: 0755

- name: Copy zookeeper configuratin file
  template:
    src: zookeeper.properties.j2
    dest: "{{ kafka_dir }}/kafka_2.12-{{ kafka_version }}/config/zookeeper.properties"
    mode: 0644
    force: yes
  notify: restart zookeeper

- name: Copy kafka configuration file
  template:
    src: server.properties.j2
    dest: "{{ kafka_dir }}/kafka_2.12-{{ kafka_version }}/config/server.properties"
    mode: 0644
    force: yes
  notify: restart kafka

- name: Copy zookeeper myid file
  template:
    src: myid.j2
    dest: "{{ zk_data_dir }}/myid"
    mode: 0644

- include: setup.yml

